services:
    admin_menu.adaptor.forms:
        class: Kunstmaan\FormBundle\Helper\Menu\FormSubmissionsMenuAdaptor
        tags:
            -  { name: admin_menu.adaptor }
    form.mailer:
        class: Kunstmaan\FormBundle\Helper\Mailer
        arguments: [@mailer, @templating]
            
    entity_id.type:
        class: Kunstmaan\FormBundle\Form\EntityIdType
        arguments: [@doctrine]
        tags:
            - { name: form.type, alias: entity_id }
                        