services:
    admin_menu.adaptor.forms:
        class: Kunstmaan\FormBundle\Helper\Menu\FormSubmissionsMenuAdaptor
        tags:
            -  { name: admin_menu.adaptor }
    form.mailer:
        class: Kunstmaan\FormBundle\Helper\Mailer
        arguments: [@mailer, @templating, @service_container]

    entity_id.type:
        class: Kunstmaan\FormBundle\Form\EntityIdType
        arguments: [@doctrine]
        tags:
            - { name: form.type, alias: entity_id }

    form.configure_sub_actions_menu_listener:
        class: Kunstmaan\FormBundle\EventListener\ConfigureActionsMenuListener
        arguments: ["@doctrine.orm.entity_manager", "@router"]
        tags:
          - { name: kernel.event_listener, event: adminnode.configureSubActionMenu, method: onSubActionMenuConfigure }
